[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 6
name = "Services"
hasChildren = true
[main.params]
isMenuLarge = true

[[main]]
parent = "Services"
name = "Computer Repairs"
pre = "<i class='dropdown-icon fas fa-tools'></i>"
post = "<small class='dropdown-subtitle'>Quick and reliable repairs to keep your business running.</small>"
url = "/services/computer-repairs"
weight = 1

[[main]]
parent = "Services"
name = "Server Management"
pre = "<i class='dropdown-icon fas fa-server'></i>"
post = "<small class='dropdown-subtitle'>Keep your servers secure and efficient.</small>"
url = "/services/server-management"
weight = 2

[[main]]
parent = "Services"
name = "Network Management"
pre = "<i class='dropdown-icon fas fa-network-wired'></i>"
post = "<small class='dropdown-subtitle'>Professional network setup and management.</small>"
url = "/services/network-management"
weight = 3

[[main]]
parent = "Services"
name = "Web Hosting"
pre = "<i class='dropdown-icon fas fa-globe'></i>"
post = "<small class='dropdown-subtitle'>Secure web hosting for your business.</small>"
url = "/services/web-hosting"
weight = 4

[[main]]
parent = "Services"
name = "Email Hosting"
pre = "<i class='dropdown-icon fas fa-envelope'></i>"
post = "<small class='dropdown-subtitle'>Secure email hosting for your business.</small>"
url = "/services/email-hosting"
weight = 5

[[main]]
parent = "Services"
name = "Microsoft 365"
pre = "<i class='dropdown-icon fas fa-map-marker-alt'></i>"
post = "<small class='dropdown-subtitle'>Track your vehicles and assets in real-time with advanced GPS solutions.</small>"
url = "/services/Microsoft-365"
weight = 6

[[main]]
parent = "Services"
name = "GPS Tracking"
pre = "<i class='dropdown-icon fas fa-map-marker-alt'></i>"
post = "<small class='dropdown-subtitle'>Track your vehicles and assets in real-time with advanced GPS solutions.</small>"
url = "/services/gps-tracking"
weight = 7

[[main]]
weight = 15
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"
weight = 10

[[main]]
parent = "Pages"
name = "FAQ"
url = "/faq"
weight = 16

[[main]]
parent = "Pages"
name = "Privacy Policy"
url = "/privacy-policy"
weight = 20

[[main]]
parent = "Pages"
name = "Terms & Conditions"
url = "/terms-conditions"
weight = 24

[[main]]
name = "Downloads"
url = "/downloads"
weight = 28

[[main]]
name = "Contact"
url = "/contact"
weight = 30

# footer menu left

[[footer_left]]
name = "Computer Repairs"
url = "/services/computer-repairs"
weight = 1

[[footer_left]]
name = "Server Management"
url = "/services/server-management"
weight = 2

[[footer_left]]
name = "Network Management"
url = "/services/network-management"
weight = 3

# footer menu middle
[[footer_middle]]
name = "Web Hosting"
url = "/services/web-hosting"
weight = 1

[[footer_middle]]
name = "Email Hosting"
url = "/services/server-management"
weight = 2

[[footer_middle]]
name = "Microsoft 365"
url = "/services/microsoft-365"
weight = 3

[[footer_middle]]
name = "Gps Tracking"
url = "/services/network-management"
weight = 4


# footer menu right

[[footer_right]]
name = "Contact"
url = "/contact"
weight = 1

[[footer_right]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2

[[footer_right]]
name = "Terms & Conditions"
url = "/terms-conditions"
weight = 3
